"use client";

import { useState } from "react";
import CalculatorLayout from "@/components/CalculatorLayout";
import { getCalculatorBySlug } from "@/lib/calculators";

const calculator = getCalculatorBySlug("random-number-generator")!;

export default function RandomNumberGenerator() {
  const [min, setMin] = useState("1");
  const [max, setMax] = useState("100");
  const [count, setCount] = useState("1");
  const [decimals, setDecimals] = useState("0");
  const [allowDuplicates, setAllowDuplicates] = useState(true);
  const [results, setResults] = useState<number[]>([]);

  const generate = () => {
    const minVal = parseFloat(min);
    const maxVal = parseFloat(max);
    const countVal = parseInt(count);
    const decimalsVal = parseInt(decimals);

    if (isNaN(minVal) || isNaN(maxVal) || isNaN(countVal) || isNaN(decimalsVal)) {
      alert("Please enter valid numbers");
      return;
    }
    if (minVal >= maxVal) {
      alert("Minimum must be less than maximum");
      return;
    }
    if (countVal < 1 || countVal > 10000) {
      alert("Count must be between 1 and 10000");
      return;
    }

    const generatedNumbers: number[] = [];
    const usedNumbers = new Set<number>();

    for (let i = 0; i < countVal; i++) {
      let randomNum: number;
      let attempts = 0;

      do {
        randomNum = minVal + Math.random() * (maxVal - minVal);
        if (decimalsVal === 0) {
          randomNum = Math.floor(randomNum);
        } else {
          randomNum = parseFloat(randomNum.toFixed(decimalsVal));
        }
        attempts++;
        if (attempts > 10000) break;
      } while (!allowDuplicates && usedNumbers.has(randomNum));

      generatedNumbers.push(randomNum);
      usedNumbers.add(randomNum);
    }

    setResults(generatedNumbers);
  };

  return (
    <CalculatorLayout
      calculator={calculator}
      formula="Random number = Min + Random() × (Max - Min). For integers, use Math.floor(). For decimals, round to specified precision using toFixed()."
      faqs={[
        { question: "Are these numbers truly random?", answer: "These are pseudo-random numbers generated by JavaScript's Math.random() function. They're suitable for most purposes but not cryptographically secure. For security-sensitive applications, use crypto.getRandomValues()." },
        { question: "What does 'allow duplicates' mean?", answer: "When enabled, the same number can appear multiple times in the results. When disabled, each generated number will be unique (if the range allows enough unique values)." },
        { question: "How many decimal places can I use?", answer: "You can specify 0-10 decimal places. 0 decimal places generates integers, while higher values generate floating-point numbers with the specified precision." },
        { question: "What's the maximum count I can generate?", answer: "You can generate up to 10,000 random numbers at once. For larger datasets, consider running the generator multiple times." }
      ]}
      howTo={[
        "Set the minimum and maximum values to define your desired range",
        "Specify how many random numbers you want to generate (1-10,000)",
        "Choose the number of decimal places: 0 for integers, or 1-10 for decimal numbers",
        "Check or uncheck 'Allow duplicates' based on whether you want unique numbers only",
        "Click Generate to create your random numbers, which will display with sum and average statistics"
      ]}
    >
      <div className="space-y-6">
        <div className="p-4 border border-gray-200 rounded-lg">
          <h3 className="font-semibold text-gray-800 mb-4">Generator Settings</h3>
          <div className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Minimum</label>
                <input type="number" value={min} onChange={(e) => setMin(e.target.value)} className="calc-input w-full" step="any" />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Maximum</label>
                <input type="number" value={max} onChange={(e) => setMax(e.target.value)} className="calc-input w-full" step="any" />
              </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Count</label>
                <input type="number" value={count} onChange={(e) => setCount(e.target.value)} className="calc-input w-full" min="1" max="10000" />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Decimal Places</label>
                <input type="number" value={decimals} onChange={(e) => setDecimals(e.target.value)} className="calc-input w-full" min="0" max="10" />
              </div>
            </div>
            <label className="flex items-center gap-2">
              <input type="checkbox" checked={allowDuplicates} onChange={(e) => setAllowDuplicates(e.target.checked)} className="w-4 h-4" />
              <span className="text-sm">Allow duplicates</span>
            </label>
          </div>
          <button onClick={generate} className="calc-btn calc-btn-primary mt-4 w-full">Generate</button>
        </div>

        {results.length > 0 && (
          <div className="result-box space-y-3">
            <h3 className="font-semibold text-gray-800">Generated Numbers ({results.length})</h3>
            <div className="max-h-96 overflow-y-auto">
              <div className="grid grid-cols-4 md:grid-cols-6 lg:grid-cols-8 gap-2">
                {results.map((num, index) => (
                  <div key={index} className="p-2 bg-gray-100 rounded text-center font-mono text-sm">
                    {num}
                  </div>
                ))}
              </div>
            </div>
            <p className="text-sm text-gray-600">
              Sum: {results.reduce((a, b) => a + b, 0).toFixed(parseInt(decimals))} | 
              Average: {(results.reduce((a, b) => a + b, 0) / results.length).toFixed(parseInt(decimals))}
            </p>
          </div>
        )}

        <div className="bg-gray-50 p-4 rounded-lg text-sm text-gray-600">
          <h3 className="font-semibold text-gray-800 mb-2">About Random Number Generator</h3>
          <ul className="list-disc list-inside space-y-1">
            <li>Generate 1-10,000 random numbers</li>
            <li>Control decimal precision (0-10 places)</li>
            <li>Option to allow or prevent duplicate numbers</li>
            <li>Displays sum and average of generated numbers</li>
          </ul>
        </div>
      </div>
    </CalculatorLayout>
  );
}
